### ISSUE TITLE
Add "capacitor" platform condition to differentiate environment 

### ISSUE THREAD

**Issue by wakqasahmed** [elastos/Elastos.Trinity.DApps.DID#31]
https://github.com/elastos/Elastos.Trinity.DApps.DID/blob/9da16b2174051e4574d6515e2dca0c8ef0a0ef9b/src/app/app.component.ts#L43

Check "capacitor" similar to "cordova" to know if the app is running in elastOS browser or as native.

**Comment by wakqasahmed** [comment]
@kpachhai @BenjaminPiette does it make sense?

**Comment by kpachhai** [comment]
Any reason we need this at this time? Since all these apps can only be run inside elastOS as of right now. We will for sure have a way to turn these apps into standalone apps in the future but I'm just wondering if we need this now as it would serve no purpose?

**Comment by BenjaminPiette** [comment]
Cordova's platform info is not very clear. We have an API in the app manager plugin, getBuildInfo(). It returns a BuildInfo object with type (elastOS, native), variant (future use) and platform (android | ios | windows | linux | macos).

Though I'm not clear why we need such check in the DID app. DID app will probably not become native for now, mostly because it's split in 2 parts, DID sessions (create dids, open sessions) and DID (everything else), which makes it hard to put together in a single native app.

**Comment by wakqasahmed** [comment]
Thanks for the detailed reply @BenjaminPiette, glad to learn how the app info is handled in app manager plugin.

Since DID app will probably not become native (for now), I am closing the issue.
